// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const RESET_LOGIN = 'RESET_LOGIN';
// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_BY_NAME = 'GET_USERS_BY_NAME';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const GET_USERS_SUCCESS_BY_ID = "GET_USERS_SUCCESS_BY_ID";
export const RESET_USER_STATE = 'RESET_USER_STATE';
export const GET_TOTAL_USERS_SUCCESS = 'GET_TOTAL_USERS_SUCCESS';

// Documents
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// Filters
export const SET_FILTER_STATE = 'SET_FILTER_STATE';
export const SET_QUERY_STATE = 'SET_QUERY_STATE';


// Shoes
export const GET_SHOES_SUCCESS = 'GET_SHOES_SUCCESS';
export const RESET_SHOE_STATE = 'RESET_SHOE_STATE';

export const SET_PAGINATION_STATE = 'SET_PAGINATION_STATE';